/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyReviewsRouteImport } from './routes/my-reviews'
import { Route as MyEnquiriesRouteImport } from './routes/my-enquiries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListYourBusinessRouteImport } from './routes/list-your-business'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as RestaurantsSlugRouteImport } from './routes/restaurants.$slug'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as DirectoryCategorySlugSlugRouteImport } from './routes/directory.$categorySlug.$slug'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReviewsRoute = MyReviewsRouteImport.update({
  id: '/my-reviews',
  path: '/my-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEnquiriesRoute = MyEnquiriesRouteImport.update({
  id: '/my-enquiries',
  path: '/my-enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourBusinessRoute = ListYourBusinessRouteImport.update({
  id: '/list-your-business',
  path: '/list-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantsRoute,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const RestaurantsSlugRoute = RestaurantsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RestaurantsRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HotelsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActivitiesRoute,
} as any)
const DirectoryCategorySlugSlugRoute =
  DirectoryCategorySlugSlugRouteImport.update({
    id: '/$categorySlug/$slug',
    path: '/$categorySlug/$slug',
    getParentRoute: () => DirectoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/my-enquiries': typeof MyEnquiriesRoute
  '/my-reviews': typeof MyReviewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/search': typeof SearchRoute
  '/tours': typeof ToursRouteWithChildren
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/directory/$categorySlug/$slug': typeof DirectoryCategorySlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/my-enquiries': typeof MyEnquiriesRoute
  '/my-reviews': typeof MyReviewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/activities': typeof ActivitiesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/tours': typeof ToursIndexRoute
  '/directory/$categorySlug/$slug': typeof DirectoryCategorySlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/my-enquiries': typeof MyEnquiriesRoute
  '/my-reviews': typeof MyReviewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/search': typeof SearchRoute
  '/tours': typeof ToursRouteWithChildren
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/directory/$categorySlug/$slug': typeof DirectoryCategorySlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/directory'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/hotels'
    | '/list-your-business'
    | '/login'
    | '/my-enquiries'
    | '/my-reviews'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/restaurants'
    | '/search'
    | '/tours'
    | '/activities/$slug'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/profile/edit'
    | '/restaurants/$slug'
    | '/tours/$slug'
    | '/activities/'
    | '/blog/'
    | '/hotels/'
    | '/restaurants/'
    | '/tours/'
    | '/directory/$categorySlug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/directory'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/list-your-business'
    | '/login'
    | '/my-enquiries'
    | '/my-reviews'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/activities/$slug'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/profile/edit'
    | '/restaurants/$slug'
    | '/tours/$slug'
    | '/activities'
    | '/blog'
    | '/hotels'
    | '/restaurants'
    | '/tours'
    | '/directory/$categorySlug/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/directory'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/hotels'
    | '/list-your-business'
    | '/login'
    | '/my-enquiries'
    | '/my-reviews'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/restaurants'
    | '/search'
    | '/tours'
    | '/activities/$slug'
    | '/blog/$slug'
    | '/hotels/$slug'
    | '/profile_/edit'
    | '/restaurants/$slug'
    | '/tours/$slug'
    | '/activities/'
    | '/blog/'
    | '/hotels/'
    | '/restaurants/'
    | '/tours/'
    | '/directory/$categorySlug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRouteWithChildren
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  ListYourBusinessRoute: typeof ListYourBusinessRoute
  LoginRoute: typeof LoginRoute
  MyEnquiriesRoute: typeof MyEnquiriesRoute
  MyReviewsRoute: typeof MyReviewsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ToursRoute: typeof ToursRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ProfileEditRoute: typeof ProfileEditRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reviews': {
      id: '/my-reviews'
      path: '/my-reviews'
      fullPath: '/my-reviews'
      preLoaderRoute: typeof MyReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-enquiries': {
      id: '/my-enquiries'
      path: '/my-enquiries'
      fullPath: '/my-enquiries'
      preLoaderRoute: typeof MyEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-business': {
      id: '/list-your-business'
      path: '/list-your-business'
      fullPath: '/list-your-business'
      preLoaderRoute: typeof ListYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/restaurants/$slug': {
      id: '/restaurants/$slug'
      path: '/$slug'
      fullPath: '/restaurants/$slug'
      preLoaderRoute: typeof RestaurantsSlugRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/directory/$categorySlug/$slug': {
      id: '/directory/$categorySlug/$slug'
      path: '/$categorySlug/$slug'
      fullPath: '/directory/$categorySlug/$slug'
      preLoaderRoute: typeof DirectoryCategorySlugSlugRouteImport
      parentRoute: typeof DirectoryRoute
    }
  }
}

interface ActivitiesRouteChildren {
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

interface DirectoryRouteChildren {
  DirectoryCategorySlugSlugRoute: typeof DirectoryCategorySlugSlugRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryCategorySlugSlugRoute: DirectoryCategorySlugSlugRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

interface HotelsRouteChildren {
  HotelsSlugRoute: typeof HotelsSlugRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsSlugRoute: HotelsSlugRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsSlugRoute: typeof RestaurantsSlugRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsSlugRoute: RestaurantsSlugRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRouteWithChildren,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HotelsRoute: HotelsRouteWithChildren,
  ListYourBusinessRoute: ListYourBusinessRoute,
  LoginRoute: LoginRoute,
  MyEnquiriesRoute: MyEnquiriesRoute,
  MyReviewsRoute: MyReviewsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SearchRoute: SearchRoute,
  ToursRoute: ToursRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ProfileEditRoute: ProfileEditRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
